### ISSUE TITLE
Check comments

### ISSUE THREAD

**Issue by wieset** [esa-prl/drivers-inclinometer_solar2#1]
See lines below
https://github.com/esa-prl/drivers-inclinometer_solar2/blob/1c7c501f98a3a582805a2f6c2403ab959e8c6e4b/src/Solar2.hpp#L33-L34

**Comment by mvoellmy** [comment]
Resolved here:
ae64a84805bac523906b9ab69eb99618d2e7878a
Turns out MAX_PACKET_SIZE doesn't need to be larger than 512. The comment must have been a leftover from earlier development stage.
